package com.action.models;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	private String name;
	
    public Library(String name) {
		super();
		this.name = name;
	}

	public String someLibraryMethod() {
        return "This is a library with the name:"+name;
    }
}
