/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.action.models.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library("setName");
        assertTrue("someLibraryMethod should return a string with the lenght greater then 0", classUnderTest.someLibraryMethod().length() > 0);
    }
}
